### ISSUE TITLE
esc/pos指令有吗

### ISSUE THREAD

**Issue by qianggewudi6666** [Liu-Jinshuai/printease#4]

**Comment by Liu-Jinshuai** [comment]
有的，[查看部分指令文档参考](https://github.com/Liu-Jinshuai/printease/tree/master/commandFile)

**Comment by qianggewudi6666** [comment]
pdf看不了，除了佳博其他打印机可以用吗

**Comment by Liu-Jinshuai** [comment]
您可以下载到本地并在本地查看。 使用github预览可能会导致加载失败。

命令是相似的。 虽然打印机品牌不同，但都支持命令，除非有些厂家不支持或者添加了个性化命令。

某些文档中显示的说明并不完整，但可以满足基本需求。 如果需要更详细的说明，可以上网查找更详细的英文文档。

**Comment by qianggewudi6666** [comment]
printease里有集成了esc吗还是要自己根据文档写一个😂

**Comment by Liu-Jinshuai** [comment]
目前只有个别指令，你可以查看[printease esc 文档](https://liu-jinshuai.github.io/printeaseDocs/src/guide/esc/print-text.html)

因为最近比较忙，添加的指令比较少，推荐你查看[自定义指令](https://liu-jinshuai.github.io/printeaseDocs/src/guide/custom-directive.html)
